### ISSUE TITLE
logo telesur

### ISSUE THREAD

**Issue by dalmore72** [Jasmeet181/mediaportal-it-logos#1]
https://www.telesurtv.net/english/tags/Italy

[telesur-vector-logo-A98D99E23E-seeklogo.com.zip](https://github.com/Jasmeet181/mediaportal-it-logos/files/1881347/telesur-vector-logo-A98D99E23E-seeklogo.com.zip)

**Comment by Jasmeet181** [comment]
I think someone has made this, it doesn't quite match and there are a few mistakes, also Inkscape doesn't support the CMYK colour space. The logo on their YouTube live streams look like [this](https://plus.google.com/photos/118206615613074383260/albums/profile/6485655890976533714?iso=false) so the text in the existing png is also wrong.
